### ISSUE TITLE
Missing data files

### ISSUE THREAD

**Issue by keggsmurph21** [letitiayhho/project_rc#3]
I think you accidentally committed the wrong files: 
 - [model_lstm/data/wikitext-2/test.txt](https://github.com/letitiayhho/project_rc/blob/master/model_lstm/data/wikitext-2/test.txt)
 - [model_lstm/data/wikitext-2/train.txt](https://github.com/letitiayhho/project_rc/blob/master/model_lstm/data/wikitext-2/train.txt)
 - [model_lstm/data/wikitext-2/valid.txt](https://github.com/letitiayhho/project_rc/blob/master/model_lstm/data/wikitext-2/valid.txt)
 - [model_rnn/data/wikitext-2/test.txt](https://github.com/letitiayhho/project_rc/blob/master/model_rnn/data/wikitext-2/test.txt)
 - [model_rnn/data/wikitext-2/train.txt](https://github.com/letitiayhho/project_rc/blob/master/model_rnn/data/wikitext-2/train.txt)
 - [model_rnn/data/wikitext-2/valid.txt](https://github.com/letitiayhho/project_rc/blob/master/model_rnn/data/wikitext-2/valid.txt)

These are all copies of the github website `html` for the files you actually want.  You need to commit the "raw" versions :^)

**Comment by letitiayhho** [comment]
wait what

also I love you

**Comment by keggsmurph21** [comment]
Where did you get the `model_*/data/wikitext-2/*.txt` files?

**Comment by letitiayhho** [comment]
https://github.com/vansky/neural-complexity/tree/master/data/wikitext-2

**Comment by keggsmurph21** [comment]
Closed by #4
